apiVersion: v1
kind: Service
metadata:
  labels:
    model.aibrix.ai/name: qwen2-5-7b-instruct
    prometheus-discovery: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
  name: qwen2-5-7b-instruct
  namespace: default
spec:
  ports:
    - name: serve
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    model.aibrix.ai/name: qwen2-5-7b-instruct
  type: LoadBalancer
