apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"model.aibrix.ai/name":"stability-deepseek-coder-7b-instruct","model.aibrix.ai/port":"8000"},"name":"stability-deepseek-coder-7b-instruct","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"model.aibrix.ai/name":"stability-deepseek-coder-7b-instruct"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"prometheus.io/path":"/metrics","prometheus.io/port":"8000","prometheus.io/scrape":"true"},"labels":{"model.aibrix.ai/name":"stability-deepseek-coder-7b-instruct"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"machine.cluster.vke.volcengine.com/gpu-name","operator":"In","values":["NVIDIA-A10","NVIDIA-L20"]}]}]}}},"containers":[{"command":["sh","-c","tail -f /dev/null"],"image":"aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/vllm-openai-v6d-dependency:v0.6.1-20241202","imagePullPolicy":"Always","name":"vllm-openai","ports":[{"containerPort":8000,"protocol":"TCP"}],"resources":{"limits":{"nvidia.com/gpu":"2"},"requests":{"nvidia.com/gpu":"2"}},"volumeMounts":[{"mountPath":"/models","name":"model-hostpath"},{"mountPath":"/dev/shm","name":"dshm"},{"mountPath":"/var/run","name":"vineyard-sock"}]},{"command":["aibrix_runtime","--port","8080"],"image":"aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/runtime:v0.1.0","imagePullPolicy":"IfNotPresent","name":"aibrix-runtime","ports":[{"containerPort":8080,"protocol":"TCP"}],"volumeMounts":[{"mountPath":"/models","name":"model-hostpath"}]}],"initContainers":[{"command":["aibrix_download","--model-uri","tos://aibrix-artifact-testing/models/deepseek-ai/deepseek-coder-6.7b-instruct/","--local-dir","/models/"],"env":[{"name":"DOWNLOADER_MODEL_NAME","value":"deepseek-coder-6.7b-instruct"},{"name":"DOWNLOADER_NUM_THREADS","value":"16"},{"name":"DOWNLOADER_ALLOW_FILE_SUFFIX","value":"json, safetensors"},{"name":"TOS_ACCESS_KEY","valueFrom":{"secretKeyRef":{"key":"TOS_ACCESS_KEY","name":"tos-credential"}}},{"name":"TOS_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"TOS_SECRET_KEY","name":"tos-credential"}}},{"name":"TOS_ENDPOINT","value":"tos-cn-beijing.ivolces.com"},{"name":"TOS_REGION","value":"cn-beijing"}],"image":"aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/runtime:v0.1.0","imagePullPolicy":"IfNotPresent","name":"init-model","volumeMounts":[{"mountPath":"/models","name":"model-hostpath"}]}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"volumes":[{"hostPath":{"path":"/root/models","type":"DirectoryOrCreate"},"name":"model-hostpath"},{"emptyDir":{"medium":"Memory","sizeLimit":"4Gi"},"name":"dshm"},{"hostPath":{"path":"/var/run/vineyard-kubernetes/vineyard-system/stability-kvintegration"},"name":"vineyard-sock"}]}}}}
  creationTimestamp: "2025-03-05T23:16:57Z"
  generation: 2
  labels:
    model.aibrix.ai/name: stability-deepseek-coder-7b-instruct
    model.aibrix.ai/port: "8000"
  name: stability-deepseek-coder-7b-instruct
  namespace: default
  resourceVersion: "145497511"
  uid: b2dd7842-bf69-4028-991d-894bf25c7541
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      model.aibrix.ai/name: stability-deepseek-coder-7b-instruct
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8000"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        model.aibrix.ai/name: stability-deepseek-coder-7b-instruct
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: machine.cluster.vke.volcengine.com/gpu-name
                operator: In
                values:
                - NVIDIA-A10
                - NVIDIA-L20
      containers:
      - command:
        - sh
        - -c
        - tail -f /dev/null
        image: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/vllm-openai-v6d-dependency:v0.6.1-20241202
        imagePullPolicy: Always
        name: vllm-openai
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: "2"
          requests:
            nvidia.com/gpu: "2"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /models
          name: model-hostpath
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /var/run
          name: vineyard-sock
      - command:
        - aibrix_runtime
        - --port
        - "8080"
        image: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/runtime:v0.1.0
        imagePullPolicy: IfNotPresent
        name: aibrix-runtime
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /models
          name: model-hostpath
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - aibrix_download
        - --model-uri
        - tos://aibrix-artifact-testing/models/deepseek-ai/deepseek-coder-6.7b-instruct/
        - --local-dir
        - /models/
        env:
        - name: DOWNLOADER_MODEL_NAME
          value: deepseek-coder-6.7b-instruct
        - name: DOWNLOADER_NUM_THREADS
          value: "16"
        - name: DOWNLOADER_ALLOW_FILE_SUFFIX
          value: json, safetensors
        - name: TOS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: TOS_ACCESS_KEY
              name: tos-credential
        - name: TOS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: TOS_SECRET_KEY
              name: tos-credential
        - name: TOS_ENDPOINT
          value: tos-cn-beijing.ivolces.com
        - name: TOS_REGION
          value: cn-beijing
        image: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/runtime:v0.1.0
        imagePullPolicy: IfNotPresent
        name: init-model
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /models
          name: model-hostpath
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /root/models
          type: DirectoryOrCreate
        name: model-hostpath
      - emptyDir:
          medium: Memory
          sizeLimit: 4Gi
        name: dshm
      - hostPath:
          path: /var/run/vineyard-kubernetes/vineyard-system/stability-kvintegration
          type: ""
        name: vineyard-sock
status:
  conditions:
  - lastTransitionTime: "2025-03-12T19:57:44Z"
    lastUpdateTime: "2025-03-12T19:57:44Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-03-12T19:57:44Z"
    lastUpdateTime: "2025-03-12T19:57:44Z"
    message: ReplicaSet "stability-deepseek-coder-7b-instruct-68ccccc6c7" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/port":"8000","prometheus.io/scrape":"true"},"labels":{"model.aibrix.ai/name":"stability-deepseek-coder-7b-instruct","prometheus-discovery":"true"},"name":"stability-deepseek-coder-7b-instruct","namespace":"default"},"spec":{"ports":[{"name":"serve","port":8000,"protocol":"TCP","targetPort":8000}],"selector":{"model.aibrix.ai/name":"stability-deepseek-coder-7b-instruct"},"type":"ClusterIP"}}
    prometheus.io/port: "8000"
    prometheus.io/scrape: "true"
  creationTimestamp: "2025-03-05T23:16:57Z"
  labels:
    model.aibrix.ai/name: stability-deepseek-coder-7b-instruct
    prometheus-discovery: "true"
  name: stability-deepseek-coder-7b-instruct
  namespace: default
  resourceVersion: "139386531"
  uid: e4ec96a2-9010-4bc3-acfc-5fc744a07c51
spec:
  clusterIP: 192.168.95.131
  clusterIPs:
  - 192.168.95.131
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: serve
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    model.aibrix.ai/name: stability-deepseek-coder-7b-instruct
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
