apiVersion: v1
kind: Service
metadata:
  name: routing-agent-service
  namespace: default
spec:
  selector:
    app: routing-agent-service
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: routing-agent-service
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 100%
  selector:
    matchLabels:
      app: routing-agent-service
  template:
    metadata:
      labels:
        app: routing-agent-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: machine.cluster.vke.volcengine.com/gpu-name
                operator: In
                values:
                - NVIDIA-L20
                # - NVIDIA-A10
      containers:
      - name: routing-agent
        image:  aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/gangmuk-routing-agent:latest
        imagePullPolicy: Always
        # image:  aibrix/gangmuk-routing-agent:latest
        # imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
            nvidia.com/gpu: 1  # Request 1 GPU
          limits:
            # cpu: "1000m"
            # memory: "1Gi"
            cpu: "5000m"
            memory: "2Gi"
            nvidia.com/gpu: 1  # Request 1 GPU
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        #   timeoutSeconds: 5
      terminationGracePeriodSeconds: 5